### ISSUE TITLE
event_instance.start() Produces no sound when running on VM in LTS v2022.0.0.12

### ISSUE THREAD

**Issue by chesrowe** [Nikkilae/fml#1]
When compiling with YYC, the ExampleGm project creates sound when calling `event_instance.start();`, but it will not if ran with the VM. This is not an issue when running with the VM on non-LTS versions of GM.

**Comment by Nikkilae** [comment]
Hi, thanks for the report. I can't seem to be able to reproduce this myself. For me everything's ok on LTS (IDE 2022.0.0.19, runtime 2022.0.0.12) as well as the older stable (IDE 2022.6.1.26, runtime 2022.6.1.40) on both VM and YYC builds. I can hear the sound that ExampleGm plays and all the auto-tests succeed.

If you have any additional info about this, please let me know!

**Comment by chesrowe** [comment]
Okay, so I'm not sure why this was the case, but for some reason running the ExampleGm project on VM caused the volume of the runner to be at 0 in the windows sound mixer. It's odd because other projects don't do it, and it doesn't change the volume on the YYC. I guess it's something weird with my system. I'm sorry for wasting your time, haha. Turning the volume up fixes the issue, just not sure why it defaulted to being all the way down.

**Comment by Nikkilae** [comment]
Ah ok, good to hear it's working! No worries.
